apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.controlPlane.namespace }}
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.controlPlane.name }}
  namespace: {{ .Values.controlPlane.namespace }}
spec:
  version: {{ .Values.controlPlane.version }}
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
