operators:
  - name: openshift-gitops-operator
    namespace: openshift-operators
    channel: latest
    source: redhat-operators
  - name: elasticsearch-operator
    namespace: openshift-operators-redhat
    channel: stable
    source: redhat-operators
    createNamespace: true
  - name: jaeger-product
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
